#theme = 'Agnes'

baseURL = "https://openpathmassagev3.netlify.app/"
languageCode = "en-us"
title = "Open Path Massage & Wellness | Erica Moore, LMT"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "All Rights Reserved, Open Path Massage"
	google_analytics_id = "GA-"
	quality = 85
    bgColor = "#fff"
    landscapePhotoWidths = [900, 800, 700, 600, 500]
    portraitPhotoWidths = [800, 700, 600, 500]
    lqipWidth = "20x"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "#"
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "#"
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		URL = "#"
		weight = 3
	
	[[menu.main]]
		Name = "Support"
		URL = "#"
		weight = 4
		
[params.social]
	TwitterURL = "https://twitter.com/podbharati"
	GoogleURL = "http://google.com"
	FacebookURL = "https://facebook.com/podbharati"
		
[params.content]
	LeadTitle = "Open Path Massage & Wellness"
	LeadDescription = "Your path to wellness through massage therapy is open!"
	ButtonCaption = "Pricing & Plans"
	ButtonURL = "#Pricing"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "In-Home Massage"
	FeatureDescription = "Relaxing massage therapy provided by a Licensed Massage Therapist in the comfort of your own home."
	FeatureImage = "images/open-path-logo-new.webp"
	
[[params.feature]]
	FeatureTitle = "Massage Packages"
	FeatureDescription = "Pre-order a massage package and save! Massage packages available for weekly, bi-weekly, or monthly in-home visits."
	FeatureImage = "images/open-path-logo-new.webp"

[[params.feature]]
	FeatureTitle = "Massage for Events"
	FeatureDescription = "Add relaxing table massage or chair massage to your office wellness program, next open house, sports massage for athletes before events, or any other event."
	FeatureImage = "images/open-path-logo-new.webp"
	
[[params.feature]]
	FeatureTitle = "Gift Certificates"
	FeatureDescription = "Prepay for a massage package or massage for a friend, family, or a coworker with a massage gift certificate."
	FeatureImage = "images/open-path-logo-new.webp"
